### ISSUE TITLE
PayPal service venmo.com

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/HttpsExclusions#1]
Please add venmo.com to the exception list. Adguard breaks it.

I think it would be great to add Venmo app to the Android exceptions:
https://play.google.com/store/apps/details?id=com.venmo&hl=en

Ticket ID: 1524207

**Comment by ameshkov** [comment]
Done

**Comment by deLumren** [comment]
Shouldn't the website be excluded from Adguard lists as well?
User 1524207 complains that site is broken when Adguard is ON in Windows.

**Comment by ameshkov** [comment]
@deLumren for now, it'd be better if he disables on that website manually. HTTPS exclusions will be updated with the next app update
