### ISSUE TITLE
HTTPS bank exclusion

### ISSUE THREAD

**Issue by ggroom** [AdguardTeam/HttpsExclusions#10]
I believe the following Australian bank website should be added to the exclusion list.

https://online.beyondbank.com.au/

**Comment by ameshkov** [comment]
Sure, thank you for reporting it!

**Comment by ggroom** [comment]
Another bank worth adding perhaps.

https://www.banksa.com.au/

**Comment by ameshkov** [comment]
@vozersky

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/HttpsExclusions/commit/ee894111d3520f8acf94867e07c1cacffb2e20ca
