### ISSUE TITLE
paper.dropbox.com

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/HttpsExclusions#11]
Can't load the page when HTTPS filtering is enabled

![screen shot 2017-05-12 at 19 22 28](https://cloud.githubusercontent.com/assets/17472907/26007374/ed18b4d2-3748-11e7-8f9f-8e92a67632f0.png)

**Comment by vozersky** [comment]
not sure if adding an exclusion is the only way to fix it though

**Comment by ameshkov** [comment]
This is a filters issue, has nothing to do with the HTTPS filtering
