### ISSUE TITLE
unable to log into pnc android app with https filtering on

### ISSUE THREAD

**Issue by jtmckinn** [AdguardTeam/HttpsExclusions#112]
It says an error has occured and won't let me login.  I disabled https filtering and it works correctly now.

**Comment by zebrum** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #2150](https://github.com/AdguardTeam/AdguardForAndroid/issues/2150) via [**ZenHub**](https://www.zenhub.com/)
