### ISSUE TITLE
VTB.ru is not fully excluded

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/HttpsExclusions#115]
In addition to i.vtb.ru which is on the list, we should exclude both **online.vtb.ru** and **vtb.ru** as customers have troubles using these websites with KIS Safe Money feature.

**Comment by karina-archazh** [comment]
Hi!
There are many similar issues on Kaspersky support page:
https://support.kaspersky.com/12692
https://support.kaspersky.com/13377
https://support.kaspersky.com/us/11976

On our side AdGuard doesn't exclude this https addresses.

**Comment by ameshkov** [comment]
@karina-archazh the point is that we should have online banking websites on the default exclusions list

**Comment by Vitalik93** [comment]
Вопрос был создан мной через поддержку. Настаиваю на добавлении сайтов в исключения HTTPS фильтрации, т.к. проблема не на стороне ЛК точно. Раз одна ссылка от ВТБ уже находится в исключениях, так почему не добавить и эти 2?
