### ISSUE TITLE
HTTPS exclusion recommendations

### ISSUE THREAD

**Issue by Termi79** [AdguardTeam/HttpsExclusions#12]
Hej!

Here are some recommendations for HTTPS exclusion:
https://www.banknorwegian.se/ (Norwegian airlines swedish banking filial)
https://www.fryksdalenssparbank.se/ (local bank in Sweden)
https://www.1822direkt.de/ (German direct bank)
https://www.1822direkt-banking.de/ (Online banking of German bank above)
https://www.volvofinans.se/ (Volvo financial services in Sweden)
https://inloggad.volvofinans.se/ (Online banking of Volvo above)
https://idpproxy.pensionsmyndigheten.se/ (online service of the Swedish pension system)
https://www.minpension.se/ (one more online service of the Swedish pension system)
https://kontakt.minavardkontakter.se/ (online service of the Swedish medical system)
https://www.forsakringskassan.se/ (online service of the Swedish insurance system)

Best regards
Daniel

**Comment by ameshkov** [comment]
Done: https://github.com/AdguardTeam/HttpsExclusions/commit/1ef1476c15f39317811564b9dcfc7656ac0e598f

Tack! :)
