### ISSUE TITLE
Credit bureaus and identity protection services

### ISSUE THREAD

**Issue by tjd2002** [AdguardTeam/HttpsExclusions#126]
US Credit reporting agencies and Identity protection sites include the most sensitive financial and personal information.

'Big 3' credit bureaus:
transunion.com
experian.com (EV cert)
equifax.com

ID protection sites from Big 3:
idnotify.com (EV cert, Experian)
completeid.com (EV cert, Experian)
trustedid.com (Equifax)
idwatchdog.com (Equifax)
trueidentity.com (TransUnion)

Other ID protection sites:
myidcare.com
lifelock.com

**Comment by TheHasagi** [comment]
Done.
