### ISSUE TITLE
binbank-online.open.ru

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/HttpsExclusions#131]
Бинбанк объединился с "Открытием", и их личный кабинет переехал на новый адрес. В связи с этим надо добавить новое исключение в банкинг-список.

**Comment by NUser2018** [comment]
> Бинбанк объединился с "Открытием", и их личный кабинет переехал на новый адрес. В связи с этим надо добавить новое исключение в банкинг-список.

Ну правильнее наверное будет назвать не личный кабинет а система Интернет-банка.
Задача создана по моей инициативе (после моего письма в техподдержку Adguard.
