### ISSUE TITLE
HTTPS filtering exclusions

### ISSUE THREAD

**Issue by simond97** [AdguardTeam/HttpsExclusions#134]
Hi, 
There should be an exclusion for:
[Tresorit ](https://tresorit.com) (encrypted cloud storage)
[Posteo](https://posteo.de) (E-Mail provider)
[Mailbox.org](https://mailbox.org) (E-Mail provider)
[ProtonMail](https://protonmail.com) (E-Mail provider)
[Tutanota](https://tutanota.com) (E-Mail provider)

Thanks guys!

**Comment by Alex-302** [comment]
Why?

**Comment by simond97** [comment]
Dropbox seems to be excluded from HTTPS filtering, so I thought other cloud services need to be added too. If I'm wrong please correct me.
<img width="585" alt="bildschirmfoto 2019-01-23 um 16 46 07" src="https://user-images.githubusercontent.com/44965501/51618332-654ccf00-1f2e-11e9-915b-d8e1827f5a60.png">

**Comment by simond97** [comment]
Alright, thanks!
