### ISSUE TITLE
list bank indonesia

### ISSUE THREAD

**Issue by 3xploiton3** [AdguardTeam/HttpsExclusions#140]
https://id.wikipedia.org/wiki/Daftar_bank_di_Indonesia

**Comment by zzebrum** [comment]
@3xploiton3 please provide the list of bank websites which needs to be added to exclusions.

**Comment by 3xploiton3** [comment]
https://ib.bankmandiri.co.id
https://ib.bri.co.id
https://ibank.klikbca.com
https://ibank.bni.co.id
https://www.cimbclicks.co.id
https://www.danamonline.com
https://new.permatanet.com
https://www.internetpanin.com
https://internetbanking.btn.co.id
https://m2u.maybank.co.id

**Comment by kurosaki98** [comment]
and this
https://online.ocbcnisp.com/
https://newvelocity.ocbcnisp.com/
https://ib.bankbjb.co.id/
https://ibank.bankmega.com
