### ISSUE TITLE
Venezuelan Banks

### ISSUE THREAD

**Issue by leninalbertolp** [AdguardTeam/HttpsExclusions#143]
## 100% Banco
`www1.100x100banco.com/IB/conexion.aspx`

`www3.100x100banco.com/ib/acceso.aspx`

## Banca Amiga
`online.bancamiga.com/?p=1`

## Banco Activo
`activoenlinea.bancoactivo.com/naturales/usuarios/login/N`

`activoenlinea.bancoactivo.com/naturales/usuarios/login/J`

## Banco Agricola
 `pcbac.com/PotalaPersonal/login.do`

`pcbac.com/PotalaCorporativa/login.do`

`secure.bancoagricola.com/clientes/`

## Banco Bicentenario
`bancaenlinea.bicentenariobu.com/#/LOGINMODI`

`bancaenlineabbu.bicentenariobu.com/IB1/IpnetBicentenario/`

## Banco Caroní
`bancocaroni.com.ve/DIBS_CARONI_VNZ/pages/loginP.jsp`

`bancocaroni.com.ve/DIBS_CARONI_VNZ/pages/loginC.jsp`

## Banco de Venezuela
`bdvenlinea.banvenez.com/login`
`e-bdv.banvenez.com/ClavenetEmpresarialRegistro/inc/BV_TopeDerecho_f10.asp`

## Bancaribe
`www3.bancaribe.com.ve/bcn/`

`www4.bancaribe.com.ve/bcj/`

## Banco del Tesoro
`enlinea.bt.gob.ve/DIBS_BDELTESORO/pages/s/login.jsp`

## Banplus
`banplusonline.com/SIBEL/ClienteNatural/Login.aspx`

`banplusonline.com/SIBEL/ClienteNatural/Login.aspx?rif=1`

## Banco Fondo Común BFC
`www4.bfc.com.ve/IBFCPersonas/`

`www3.bfc.com.ve/IBFCjuridicos/`

## Banco Exterior
`nexopersonas-bancoexterior.com/internetbanking/`

`nexojuridico-bancoexterior.com/portaljuridico/`

## Banco Mercantil
`www30.mercantilbanco.com/olb/InitMerc?from=index`

`portaldepagosmercantil.com/`

## Banco Nacional de Crédito BNC
`secure.bnc.com.ve/`

`efectivo.bnc.com.ve/`

## Banco Occidental de Descuento BOD
`web.bancadigitalbod.com/nblee6/f/ext/Login/index.xhtml`

## Banco Plaza
`bancaenlinea.bancoplaza.com/personas/`

`bancaenlinea.bancoplaza.com/empresas/`

## Banco Provincial
`bbvaprovinet.provincial.com/WCPL_VE_WEB/wcpl_ve_web/provinet/BBVAInicioWC.jsp`

## Banco Venezolano de Credito
`vol.venezolano.com/`

`vob.venezolano.com/`

## Bancrecer
`bancrecerdigital.com/bankzilla_bancrecer_front/login.jsp?action=no_session`

## Delsur Banco Universal
`delsuronline.com.ve/BancaPorInternet/BPSignOnAction?var=c4ca4238a0b923820dccx108aa59aa0aa40ccx509a6f75849b`

`delsuronline.com.ve/BancaPorInternet/LoginEmpresas`

## Sofitasa
`sofinet.com.ve:4443/E1F/initAppn1.start()`

`sofinet.com.ve:4443/E1F/initAppj1.start()`

## Banesco
`banesconline.com/mantis/Website/Login.aspx`

`solicitudestarjetas.banesco.net/`

`banesconline.com/SIF/index.html`

`solicitudes.banesco.com/BanescoWeb/faces/portal/login/login.xhtml`

`pagoelectronico.banesco.com/lazaro/Website/login.aspx`

**Comment by TheHasagi** [comment]
Done.
