### ISSUE TITLE
Domains of Banks to be Excluded (Taiwan)

### ISSUE THREAD

**Issue by HJ-zhtw** [AdguardTeam/HttpsExclusions#145]
60.251.84.21
ctbcbank.com
taishinbank.com.tw
esunbank.com.tw
scsb.com.tw
mybank.com.tw
bot.com.tw
dbs.com.tw
sinopac.com
hncb.com.tw
ubot.com.tw
firstbank.com.tw
tcb-bank.com.tw
ktb.com.tw
chb.com.tw
bok.com.tw
hsbc.com.tw
hwataibank.com.tw
naffic.org.tw
megabank.com.tw
richart.tw
o-bank.com
landbank.com.tw
kokobank.com
bop.com.tw
kh3c.com.tw
chinatrust.com
ch6c.com.tw
hua215.com.tw
taipeistarbank.com.tw
sunnybank.com.tw
standardchartered.com.tw
citibank.com.tw
yuantabank.com.tw
feib.com.tw
fubon.com
taipeifubon.com.tw
jihsunbank.com.tw
entiebank.com.tw
cotabank.com.tw
skbank.com.tw
scu.org.tw
kgibank.com
tcbbank.com.tw

**Comment by HJ-zhtw** [comment]
#New

216.58.192.0 - 216.58.223.255
ctbcbank.com
202.6.104.0 - 202.6.105.255
jkopay.com    *
post.gov.tw    *
twmp.com.tw

**Comment by TheHasagi** [comment]
Done.

**Comment by HJ-zhtw** [comment]
#NEW

nccc.com.tw
