### ISSUE TITLE
tk-barn.ru

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/HttpsExclusions#146]
### Issue URL (Incorrect Blocking)
[https://tk-barn.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Ftk-barn.ru%2F)
### Comment
> Исправили добавив tk-barn.ru в исключения HTTPS.
> 
> --
> Информация ниже сгенерирована автоматически, не удаляйте ее.
> 
> Referrer:
> 
> 
> Custom userscripts:
> https://cdn.adguard.com/public/Userscripts/Wot/1.0/wot.meta.js
> https://cdn.adguard.com/public/Userscripts/AdguardAssistant/4.2/assistant.meta.js
> https://cdn.adguard.com/public/Userscripts/AdguardPopupBlocker/2.5/popupblocker.meta.js

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/87ZFwQv.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/LEVINaY.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Mac
AdGuard version: | 2.0.0.524 nightly
Browser: | Chrome
Filters: | AdGuard Russian,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

**Comment by Eugene-Savenko** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/31578

**Comment by zzebrum** [comment]
@Eugene-Savenko it seems to CL bug

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/CoreLibs #823](https://github.com/AdguardTeam/CoreLibs/issues/823) via [**ZenHub**](https://www.zenhub.com/)
