### ISSUE TITLE
agenciatributaria.gob.es

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/HttpsExclusions#15]
https://www.agenciatributaria.gob.es  Is the official website of the Tax agency in Spain. They use a digital certificate to access. When AG is running even if all the filters are disabled - the web can not access the certificate. Only solution is to close AG completely to make it work.

https://github.com/AdguardTeam/AdguardFilters/issues/3956

**Comment by ameshkov** [comment]
Thank you!
