### ISSUE TITLE
Indonesian internet banking exclusion

### ISSUE THREAD

**Issue by KrisNM** [AdguardTeam/HttpsExclusions#171]
#BCA (Bank Central Asia) 
m.klikbca.com (mobile login site redirected to this address, ibank prefix for the desktop) 
klikpay.klikbca.com
www.klikbca.com
#
#BRI (Bank Rakyat Indonesia) 
mobile.bri.co.id (used by its app)
#
#Bank Permata
new.permatanet.com
#
#Citibank Indonesia
www.citibank.co.id
#
#HSBC Indonesia
www.hsbc.co.id

Regards.

**Comment by 3xploiton3** [comment]
Add
bca.co.id
