### ISSUE TITLE
monzo.com - whitelist bank

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/HttpsExclusions#172]
@LewisLebentz commented on [Mon Apr 22 2019](https://github.com/AdguardTeam/AdguardFilters/issues/32893)

Please add:

* monzo.com

To the HTTPS Filtering whitelist, they're a bank in the UK so shouldn't have their traffic inspected by AdGuard.

**Comment by TheHasagi** [comment]
Done.
