### ISSUE TITLE
Nationwide.co.uk

### ISSUE THREAD

**Issue by BrokenHope** [AdguardTeam/HttpsExclusions#173]
The UK Building Society Nationwide at the following website nationwide.co.uk isn't on the HTTPS exclusion list.

**Comment by TheHasagi** [comment]
Done.

**Comment by Eugene-Savenko** [comment]
There's a typo:

![image](https://user-images.githubusercontent.com/15856304/88170485-71e6dc00-cc26-11ea-88b2-c6a8c56bf030.png)
