### ISSUE TITLE
Domains of Banks/Mobile Payment to be Excluded (Taiwan)

### ISSUE THREAD

**Issue by HJ-zhtw** [AdguardTeam/HttpsExclusions#174]
#NEW

nccc.com.tw
↑ An organization processes some trading informations. E.g. 3D Authentication.

...To be Completed

**Comment by HJ-zhtw** [comment]
gov.tw         *governmental

**Comment by HJ-zhtw** [comment]
edu.tw
↑Educational, usually includes many private informations.

**Comment by TheHasagi** [comment]
Already in the lists.
