### ISSUE TITLE
Colombian Banks to be excluded

### ISSUE THREAD

**Issue by wco** [AdguardTeam/HttpsExclusions#175]
bancodebogota.com
bancopopular.com.co
itau.co
grupobancolombia.com
transaccionesbancolombia.com
citibank.com.co
gnbsudameris.com.co
bbva.com.co
colpatria.com
colpatria.com.co
bancodeoccidente.com.co
bancoldex.com
bancocajasocial.com
bancoagrario.gov.co
bancoagrario.gov.co
davivienda.com
avvillas.com.co
bancow.com.co
bancoprocredit.com.co
bancamia.com.co
bancopichincha.com.co
bancoomeva.com.co
bancofalabella.com.co
bancofinandina.com
santander.com.co
coopcentral.com.co

**Comment by TheHasagi** [comment]
None conflicts were found.
