### ISSUE TITLE
Remove meduza.io

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/HttpsExclusions#178]
Пожалуйста, фильтруйте сайт [meduza.io](meduza.io), даже если включена опция `Не фильтровать сайты с SSL EV сертификатами`, т. к. на meduza.io есть реклама, но нет каких-либо чувствительных данных, которые может оставить пользователь.

**Comment by zzebrum** [comment]
Вы можете добавить нужные вам сайты в исключения.
