### ISSUE TITLE
apps.cybonline.co.uk

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/HttpsExclusions#186]
Adguard interferes with the secure login to the Internet Banking service of my new bank.

https://apps.cybonline.co.uk/cyb/authenticate/yb/challenge?currentChallenge=date_of_birth&client_id=yb_web&state=1b5cedec-b516-48ff-96af-70395bfb6238&scope=30&response_type=token&redirect_uri=https%3A%2F%2Fcybg.ybonline.co.uk%2Fcyb%2Fonline-banking%2Fbapp%2Fauthentication%3FapplyFor%3DIM135

**Comment by TheHasagi** [comment]
Done.
