### ISSUE TITLE
PingFederate Single SignOn blocks the POST request submitted by Adguard

### ISSUE THREAD

**Issue by crbhaskar** [AdguardTeam/HttpsExclusions#191]
[Diabling_Adguard_Validation_FT_SSO.docx](https://github.com/AdguardTeam/HttpsExclusions/files/3590010/Diabling_Adguard_Validation_FT_SSO.docx)
We are using the Single-SignOn (Browser based SSO) in www.franklintempleton.com website to allow the end users to navigate between multiple applications of franklintempleton by single login. The profile.franklintempleton.com will act as an IDP application and the www.franklintempleton.com and the accounts.franklintempleton.com will act as a SP application. Additionally we are using a product called Pingfederate to generate/consume the SAML assertions and provide the tokens for us. This Pingfederate product is NOT accepting the POST request submitted by Adguard instead of browser. Pingfederate product considers the Adguard interrupted requests as suspicious requests. This situation blocks the end user landing in the service provider application.
Atpresent, we are asking end users to add our domain in the HTTPS exclustions. Instead, if you have added the exclusion, then it will be good.

**Comment by ameshkov** [comment]
Got it, thank you!

So it'd be enough to exclude `profile.franklintempleton.com`, right?

**Comment by crbhaskar** [comment]
HI Andrey Meshkov,

Yes.. That is correct.

Thanks and Regards,
Bhaskar

**Comment by ameshkov** [comment]
Added it. New versions of AdGuard will have https filtering disabled for this domain by default.

**Comment by crbhaskar** [comment]
Thank you

**Comment by crbhaskar** [comment]
Hi Adguard Team,

Thank you for the expeditious reply, we have a high net worth client that we owe an update when they can attempt again, without turning off Adguard.

He leverages Adguard in Mac OS Mojave, can you please relay when below update will be applied, so we can update our client?

Thank You,
Jeff

From: Ramasamy, Bhaskar <bhaskar.ramasamy@franklintempleton.com>
Sent: Monday, September 9, 2019 6:46 AM
To: AdguardTeam/HttpsExclusions <reply@reply.github.com>; AdguardTeam/HttpsExclusions <HttpsExclusions@noreply.github.com>
Cc: Author <author@noreply.github.com>; Metz, Jeff P. <jeffrey.metz@franklintempleton.com>; Araie Ardakani, Arezoo <arezoo.araieardakani@franklintempleton.ca>
Subject: RE: [AdguardTeam/HttpsExclusions] PingFederate Single SignOn blocks the POST request submitted by Adguard (#191)

HI Andrey Meshkov,

Yes.. That is correct.

Thanks and Regards,
Bhaskar

**Comment by ameshkov** [comment]
@crbhaskar 

> He leverages Adguard in Mac OS Mojave, can you please relay when below update will be applied, so we can update our client?

There will be a minor update in a month or so.

**Comment by crbhaskar** [comment]
Hi Adguard Team,

Can you please provide an update on the below question, when update will be pushed to production for OS Mac Mojave?

If needed, I can submit another request via your portal for this answer, just let me know.  Otherwise a date when we can expect a date for the patch to be released to production, this way we can update our client.

Thank You,
Jeff

From: Metz, Jeff P. <jeffrey.metz@franklintempleton.com>
Sent: Monday, September 9, 2019 7:58 AM
To: Ramasamy, Bhaskar <bhaskar.ramasamy@franklintempleton.com>; AdguardTeam/HttpsExclusions <reply@reply.github.com>; AdguardTeam/HttpsExclusions <HttpsExclusions@noreply.github.com>
Cc: Author <author@noreply.github.com>; Araie Ardakani, Arezoo <arezoo.araieardakani@franklintempleton.ca>
Subject: RE: [AdguardTeam/HttpsExclusions] PingFederate Single SignOn blocks the POST request submitted by Adguard (#191)

Hi Adguard Team,

Thank you for the expeditious reply, we have a high net worth client that we owe an update when they can attempt again, without turning off Adguard.

He leverages Adguard in Mac OS Mojave, can you please relay when below update will be applied, so we can update our client?

Thank You,
Jeff

From: Ramasamy, Bhaskar <bhaskar.ramasamy@franklintempleton.com<mailto:bhaskar.ramasamy@franklintempleton.com>>
Sent: Monday, September 9, 2019 6:46 AM
To: AdguardTeam/HttpsExclusions <reply@reply.github.com<mailto:reply@reply.github.com>>; AdguardTeam/HttpsExclusions <HttpsExclusions@noreply.github.com<mailto:HttpsExclusions@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>; Metz, Jeff P. <jeffrey.metz@franklintempleton.com<mailto:jeffrey.metz@franklintempleton.com>>; Araie Ardakani, Arezoo <arezoo.araieardakani@franklintempleton.ca<mailto:arezoo.araieardakani@franklintempleton.ca>>
Subject: RE: [AdguardTeam/HttpsExclusions] PingFederate Single SignOn blocks the POST request submitted by Adguard (#191)

HI Andrey Meshkov,

Yes.. That is correct.

Thanks and Regards,
Bhaskar

**Comment by ameshkov** [comment]
This change will be included in the AdGuard for Mac version 2.2 release which is expected to be released in the middle of October. I can't say the exact date at this point, a lot depends on how the beta test goes.

**Comment by crbhaskar** [comment]
Hi Adguard Team,

Apologies for unknowingly reviewing github for updates and see the update there, thank you Andrey Meshkov for the reply.   Please ignore my below email.

Pasting Andrey’s response for others to see the feedback:

**Comment by jmetz272003** [comment]
Hi Andrey Meshkov, 

Thank you for the great support to date!  

Really appreciated, I’ve since joined github and unable to reply off closed issue 191.  

Can you please confirm if a production date has been derived for your below comment/patch relayed last month and this patch will include the fix?   If easier I can reopen Issue 191 or submit a new request via github, just let us know. 

This change will be included in the AdGuard for Mac version 2.2 release which is expected to be released in the middle of October. I can't say the exact date at this point, a lot depends on how the beta test goes.

Thank You, 
Jeff
