### ISSUE TITLE
Прошу добавить исключения

### ISSUE THREAD

**Issue by prokosha002** [AdguardTeam/HttpsExclusions#194]
online.gpb.ru
binance.com
bitmex.com
dsx.uk
poloniex.com
hbg.com
myetherwallet.com
bitfinex.com
walletgenerator.net
login.blockchain.com
my.epayments.com
hitbtc.com
international.bittrex.com
ru.bitstamp.net
bitmart.com

**Comment by TheHasagi** [comment]
Все, кроме `online.gpb.ru` не являются банковскими сайтами, а относятся к криптовалютным площадкам с которыми при фильтрации проблем нет никаких.
