### ISSUE TITLE
hubank.com

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/HttpsExclusions#2]
add https://www.hubank.com/ to https exclusions 

![screenshot 2017-04-06 12 48 13](https://cloud.githubusercontent.com/assets/23637588/24748106/506491ee-1ac7-11e7-9c1a-285216b5400c.png)

**Comment by ameshkov** [comment]
Done

**Comment by OlegSUP** [comment]
@ameshkov Please check hubank.com. We just had a call from our customer, and she complained that adguard breaks it. Also I have Adguard Assistant on it:

<details>

![screen shot 2017-04-10 at 9 05 49 pm](https://cloud.githubusercontent.com/assets/26434103/24875821/0b6aaac4-1e32-11e7-968b-30c20ebe88bb.png)


</details>

**Comment by ameshkov** [comment]
@OlegSUP we have added, but it won't get to the customer's exceptions without a program update.

For now customer should add `hubank.com` to the HTTPS exclusions manually.

**Comment by OlegSUP** [comment]
Ok, will forward this information. Thank you!
