### ISSUE TITLE
Add bank site to exclusions

### ISSUE THREAD

**Issue by R3gi** [AdguardTeam/HttpsExclusions#201]
Please add following URLs to bank exclusion list:

- `hlidej.mojezdravefinance.cz` (finantial app – internet banking addon)
- `george.csas.cz` (internet banking)

Thanks

**Comment by TheHasagi** [comment]
csas.cz already in the exclusion list. To add the app to the exclusions please, create an issue in a proper [repository](https://github.com/adguardteam/adguardforandroid/issues/new).
