### ISSUE TITLE
Изменить HTTPS-исключения для одного из банков

### ISSUE THREAD

**Issue by NUser2018** [AdguardTeam/HttpsExclusions#208]
1) У банка "Открытие" изменился адрес системы Интернет-банка с **online.open.ru** на **ib.open.ru**. Логичным было бы просто заменить имеющееся  HTTPS-исключение на новое. **_Но сначала смотрите п.2_**.
Для системы интернет-банка бывших клиентов "Бинбанка" (ранее "Бинбанк" объединился с  "Открытие") адрес уже есть в  HTTPS-исключениях **binbank-online.open.ru**

2) **_Но у меня есть другое предложение, которое лучше, шире и включит в себя п.1, подробнее далее:_**

У Adguard (как минимум для Windows, а возможно и для Mac) есть одна известная давняя проблема совместимости с антивирусными продуктами Лаборатории Касперского (при включенном WFP-драйвере): если сайт открывается антивирусом в режиме **Безопасных платежей**, но при этом этот сайт отсутствует в  HTTPS-исключениях Adguard, то возникает ошибка сертификата.  Проблема давно уже и на текущий момент решается только добавлением нужного адреса в HTTPS-исключения Adguard.

Так вот поскольку антивирус предлагает переход в режим **Безопасных платежей** сразу при открытии сайта банка **open.ru** то необходимо добавить в HTTPS-исключения Adguard именно это более широкое исключение **open.ru** (_так же как сделано для Сбербанка **sberbank.ru**_)

А более узкие исключения **online.open.ru** и **ib.open.ru** и **binbank-online.open.ru** тогда можно (и нужно) удалить, поскольку они будут покрыватся более широким исключением **open.ru**

**Comment by NUser2018** [comment]
То что добавили **open.ru** это здорово, спасибо.
Но почему не удалили **online.open.ru** и **binbank-online.open.ru** необходимости в которых больше не будет, поскольку они покрываются новым более широким исключением **open.ru**!?
Зачем захламлять список исключений дублирующими исключениями, которые теперь будут не нужны?

**Comment by NUser2018** [comment]
И **ib.open.ru** также не нужно было добавлять. Оно также покрывается новым более широким исключением **open.ru**!

**Comment by TheHasagi** [comment]
@NUser2018 

Пока эти домены еще актуальные. Конкретно на поддомены open.ru все же стоит оставить, как только выше перечисленные изменения вступят силу - уберу. Для этого есть отдельная [задача](https://github.com/AdguardTeam/HttpsExclusions/issues/24) по актуализации списка.

**Comment by NUser2018** [comment]
Изменения вступают в силу и выходят в релиз только в рамках следующей версии (например Adguard для Windows 7.3)? Списки HTTPS-исключений не обновляются же автоматически как это происходит с фильтрами и расширениями? Я все верно понимаю?

**Comment by TheHasagi** [comment]
@NUser2018  

Изменения вступают в силу с выходом релизной версии, стараемся добавлять и в выходящие найтли/бета версии продукта. В следующей найтли версии изменения появятся.

**Comment by NUser2018** [comment]
@TheHasagi  Обновился до релизной версии **7.3 (7.3.3048)** то что **open.ru** вошел в список HTTPS-исключений по умолчанию это хорошо. Но зачем же там так и остались **ib.open.ru** **online.open.ru** **binbank-online.open.ru** !? Они ведь перекрываются новым исключением **open.ru**. И ранее здесь в обсуждении Вы обещали лишнее убрать.

**Comment by ameshkov** [comment]
@TheHasagi ping, не забудь

**Comment by TheHasagi** [comment]
Done.
