### ISSUE TITLE
Exclusion List Production Release Date?

### ISSUE THREAD

**Issue by jmetz272003** [AdguardTeam/HttpsExclusions#210]
Hello,  We owe our client of Franklin Templeton an update hence asking for update here.  
 
Has a date been derived for exclusion list to migrate to production?  

Last update was in Issue 205 and previously 191, and adding comments to closed issues hasn't netted any replies hence opening a new issue.  

Thank You, 
Jeff

From: zzebrum <notifications@github.com> 
Sent: Thursday, October 10, 2019 11:09 AM
To: AdguardTeam/HttpsExclusions <HttpsExclusions@noreply.github.com>
Cc: Metz, Jeff P. <jeffrey.metz@franklintempleton.com>; Mention <mention@noreply.github.com>
Subject: Re: [AdguardTeam/HttpsExclusions] Release Date for AdGuard for Mac version 2.2? (#205)

@jmetz272003 hello there! Currently, we are preparing for the first beta. I'll try to manage to update the exclusions list earlier.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe

**Comment by jmetz272003** [comment]
Hello, can someone please provide an update?  Thank you.

**Comment by ameshkov** [comment]
Hi @jmetz272003 and sorry for the late reply!

The current ETA for the v2.2 release is 2-3 weeks from now. We've almost finished everything we planned.
