### ISSUE TITLE
ing.de is not excluded

### ISSUE THREAD

**Issue by oliverandrich** [AdguardTeam/HttpsExclusions#217]
Hi,

I just wanted to drop you an issue, that ing.de is not excluded from https filtering even so it is included in your exceptions document for banks. May be the reason is, that officially they are ing.de but still use ing-diba.de under the hood.

<img width="509" alt="Bildschirmfoto 2019-11-11 um 23 41 35" src="https://user-images.githubusercontent.com/758/68626953-d456dc80-04dc-11ea-8afa-1cd915776a99.png">

Best regards
Oliver

**Comment by TheHasagi** [comment]
@oliverandrich 

Thank you!
