### ISSUE TITLE
Adding new banks to https exclusions

### ISSUE THREAD

**Issue by dariovernelli** [AdguardTeam/HttpsExclusions#232]
Hi,

I'd like to add new domains for banks url to https exclusions either on mac app and on android app:
fineco.it
hellobank.it
intesasanpaolo.com
generali.it

Is it possible to do myself or you have to add them into the filter updates ?

Thanks
Dario

**Comment by slavaleleka** [comment]
@dariovernelli it's possible. if you know how to do it by your own, you can make pull request
