### ISSUE TITLE
Missing Philippine banks

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/HttpsExclusions#251]
- bdo.com.ph
- bpi.com.ph
- pnb.com.ph
- chinabank.ph
- bancnetonline.com (from dbp.ph)
- devbnkphl.com (from dbp.ph)
- rcbconline-corporate.com
- rcbconlinebanking.com
- unionbankph.com
- eastwestbanker.com
- ucpb.biz
- citibank.com.ph
- asiaunited.com.ph

**Comment by TheHasagi** [comment]
Merged.
