### ISSUE TITLE
Add more Brazilian banks and financial institutions to HTTPS exclude list

### ISSUE THREAD

**Issue by dbolivar** [AdguardTeam/HttpsExclusions#265]
Add these Brazilian banks and financial institutions to the HTTPS exclude list:

agorainvestimentos.com.br
bradesco.com.br
btgpactualdigital.com.br
credicard.com.br
foxbit.com.br
mercadobitcoin.com.br
sofisadireto.com.br
xpi.com.br

**Comment by fer-nando** [comment]
Please add to the list:
cav.receita.fazenda.gov.br
