### ISSUE TITLE
Google Services

### ISSUE THREAD

**Issue by EusebiuOprinoiu** [AdguardTeam/HttpsExclusions#273]
Please, add these 2 Google subdomains to HTTPS exclusions.
The first one is for Google Search Console and the second one is for the Google Analytics dashboard.
Right now, AdGuard breaks some functionality when HTTPS filtering is enabled, the worse one being in Google Analytics, where admins no longer have access to their properties.

search.google.com
analytics.google.com

**Comment by TheHasagi** [comment]
@EusebiuOprinoiu 

Unfortunately, those domains cannot be whitelisted. To work with the tools you want you can just exclude certain websites manually.
