### ISSUE TITLE
Banks

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/HttpsExclusions#29]
bankofbeirut.com
arabbank.com.lb
bankaudi.com.lb
bankmed.com.lb
byblosbank.com.lb
blombank.com
lgbbank.com
bbacbank.com
meabank.com
feniciabank.com
fnb.com.lb

danskebank.dk
nordea.com
jyskebank.dk
mitnykredit.dk
creditbank.com.lb
creditbank.com
nykredit.dk
sydbank.dk

**Comment by vozersky** [comment]
nordea.com is in the list already :)

Added, thanks!
