### ISSUE TITLE
https://regal88.net/EN/home.aspx

### ISSUE THREAD

**Issue by lohsiewweng** [AdguardTeam/HttpsExclusions#294]
i want block this website.example this https://regal88.net/EN/home.aspx
Suppose I want to intercept this gambling evil web site, how not to be social depravity?

**Comment by zzebrum** [comment]
@lohsiewweng well, AdGuard does not block access to any web site, it is up to the user to decide. But we have our own phishing and malware databases to protect our users. If you are using AdGuard products then enable Phishing and malware protection in settings.
