### ISSUE TITLE
Exclusions

### ISSUE THREAD

**Issue by NicoPass** [AdguardTeam/HttpsExclusions#33]
Hello,

Can you exclude bcj.ch (Cantonal Bank of Jura) and icorner.ch (Corner Banca)?

Thank you

**Comment by vozersky** [comment]
@NicoPass hello! sure, thanks for reporting them

**Comment by vozersky** [comment]
Added https://github.com/AdguardTeam/HttpsExclusions/commit/0f8bd391eef00ebdb165a4afb1e9e5b59ee7aa73   thanks!
