### ISSUE TITLE
dls.hkjunkcall.com for headuckblocker

### ISSUE THREAD

**Issue by pekkle-hksar** [AdguardTeam/HttpsExclusions#333]
Hi,

Would like to request to add the following to the whitelist.

`dls.hkjunkcall.com$app=com.headuck.headuckblocker.dev
`
It is used by a call filtering app in Hong Kong (com.headuck.headuckblocker.dev) to download the junk call list.

**Comment by Chinaski1** [comment]
Hello there!

Please, provide the link to download the specified app to test.

**Comment by pekkle-hksar** [comment]
https://play.google.com/store/apps/details?id=com.headuck.headuckblocker.dev

or

http://blog.headuck.com/測試版/

**Comment by zzebrum** [comment]
It seems like AdGuard does not block this request.
