### ISSUE TITLE
"Filter websites with an Extended Validation Certificate"

### ISSUE THREAD

**Issue by jawz101** [AdguardTeam/HttpsExclusions#342]
By default this is enabled.  Does this mean these sites are filtered or excluded from filtering? ( skipped) 

The help file suggests the defaults do not filter on EV certs so either the wording is incorrect or the default is incorrect.

**Comment by ameshkov** [comment]
>  Does this mean these sites are filtered or excluded from filtering?

By default, they are filtered.

> The help file suggests the defaults do not filter on EV certs so either the wording is incorrect or the default is incorrect.

Could you please tell me where it states that?

**Comment by jawz101** [comment]
> 
> 
> > Does this mean these sites are filtered or excluded from filtering?
> 
> By default, they are filtered.
> 
> > The help file suggests the defaults do not filter on EV certs so either the wording is incorrect or the default is incorrect.
> 
> Could you please tell me where it states that?

https://kb.adguard.com/en/general/https-filtering

> AdGuard provides an ability to exclude from filtering all websites that use extended validation certificates.

I just wiped my settings, reinstalled HTTPS certificate, and the defalult is toggled/enabled to "Filter websites with an Extended Validation (EV) Certificate".

myaccount.google.com has an EV certificate.  I browse to myaccount.google.com in Chrome and look at the certificate details and it says "Google Chrome verified that AdGuard Personal CA issued this website's certificate."

Regardless of if I have the filter websites with an EV certificate, AdGuard CA still shows in the certificate chain unless I explicitly add that domain to the whitelist.  Therefore, the EV certificate toggle doesn't do anything.

**Comment by ameshkov** [comment]
Sorry, I am not getting it.

I just said that by default it **does filter sites with EV certs** meaning HTTPS filtering, not filtering out.

> AdGuard provides an ability to exclude from filtering all websites that use extended validation certificates.

Yes, there's an option, there's no statement on the default behavior.

**Comment by jawz101** [comment]
Whether I toggle the setting or not, the only way to exclude myaccount.google.com is to add myaccount.google.com to the whitelist.

**Comment by ameshkov** [comment]
@jawz101 the cert on myaccount.google.com is not EV.

Here's how to distinguish EV certs in Chrome -- look at the website details, if you see the organization name and "Issued to:" -- this is an EV cert.

![image](https://user-images.githubusercontent.com/5947035/99300699-fb698c00-285d-11eb-8551-280b12900bc2.png)
