### ISSUE TITLE
Add Zoom domains to the HTTPS exclusions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/HttpsExclusions#357]
Here's what you need to do:

1. Move the cert to the system storage
2. Figure out which domains lead to this warning
3. Add these domains to the HTTPS exclusions

![image](https://user-images.githubusercontent.com/5947035/102049283-a33c9000-3df1-11eb-8020-3b11365ac3de.png)

**Comment by Chinaski1** [comment]
zoom.us
