### ISSUE TITLE
HTTPS Exclusions - Australia

### ISSUE THREAD

**Issue by aussiefella74** [AdguardTeam/HttpsExclusions#361]
Hello, 

Can you please add the following urls to your https exclusion list:

https://www.bankfirst.com.au
https://ibank.bankfirst.com.au/desktop/signon/login.aspx
https://www.ing.com.au/securebanking/
https://www.selfwealth.com.au
https://secure.selfwealth.com.au/Account/Login
https://portfolio.sharesight.com/login
https://www.computershare.com/au
https://login-au.computershare.com/identity/run/Login?wid=TP7rJjc070elWYQLdEantQ&theme=CPU#EnterUserId
https://www.vicsuper.com.au
https://idp.vicsuper.com.au/idp/startSSO.ping?PartnerSpId=https://online.vicsuper.com.au/sonataweb/saml
https://www.coinspot.com.au/login
https://www.independentreserve.com
https://app.independentreserve.com/login
https://1password.com
https://start.1password.com/signin
https://appleid.apple.com

Thank you very much

Aussie

**Comment by Chinaski1** [comment]
appleid.apple.com - we do not filter this domain by default.
1password.com - I don't think it makes sense to add this domain to the exceptions.
The other domains have been added to the HTTPS exceptions, thanks for the information provided.

**Comment by aussiefella74** [comment]
Hi Konstantin, thanks for your notes on those two domains and for adding
the rest to the list.

Regards,

Aussie
