### ISSUE TITLE
TomTom AmiGO 

### ISSUE THREAD

**Issue by VincenzoVitale-TomTom** [AdguardTeam/HttpsExclusions#370]
Hello,
multiple users of the TomTom AmiGO app are reporting problems when AdGuard is used. 
In AmiGO we use certificate pinning to restrict to a minimum the accepted certificates, that is why the HTTP filtering in AdGuard causes requests to fail.

[AmiGO](https://play.google.com/store/apps/details?id=com.tomtom.speedcams.android.map) is a free navigation application with no advertisement and TomTom will never sell customer data to others. That is also what differentiate the AmiGO app (and the entire TomTom) from other free navigation applications.

As also discussed by email, could you please add the following urls to the exclusion list:
```
scmts.tomtom.com
api.tomtom.com
test.api-system.tomtom.com/ (nk2 we use in beta)
appanalytics.tomtom.com
www.leanplum.com
```

Important note, we tried to add the URLs in AdGuard to check if that would solve the problems, but the app still didn't work.
The only action that seemed to work was when we requested AdGuard to not block the entire app. 
Is it possible to add an entire verified application to a default exclusion list?

Thanks,
V.

**Comment by ameshkov** [comment]
Got it, thank you for reporting it!

> Is it possible to add an entire verified application to a default exclusion list?

Yes, I guess it'd be easier to disable HTTPS filtering for the app by default.
However, users may still decide to enable it on their own (even though AdGuard will warn them that this is not recommended).

One important note here - by default AdGuard does not attempt to filter HTTPS in apps that target SDK level 23 or higher unless the user has root access and manually moved AdGuard CA to the system certs store. This is just a tiny share of all users, everything should be okay for others.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #3718](https://github.com/AdguardTeam/AdguardForAndroid/issues/3718) via [**ZenHub**](https://www.zenhub.com/)

**Comment by VincenzoVitale-TomTom** [comment]
Thanks @ameshkov!
Also for choosing to disable the filtering with AmiGO by default, in that way we do not need to maintain the list updated if we add new urls.

Mhmm, from what you are saying then AmiGO should have worked since we target sdk 29. that would also explain why adding those url to the whitelist didn't have any effect.

Is there something else that is disabled when adguard is disabled via the app management settings?

**Comment by ameshkov** [comment]
> Is there something else that is disabled when adguard is disabled via the app management settings?

So here're three things to check:

1. Disabling HTTPS filtering (should be unchecked unless you're on a rooted device)
2. Disabling "ad blocking" - in this case, AdGuard will proxy all the app traffic, but won't change it
3. Disabling it completely - in this case, AdGuard will not route the app traffic through the local VPN tunnel, i.e. won't touch it all.

Does it help if you don't disable filtering completely, but just disable ad blocking?

**Comment by VincenzoVitale-TomTom** [comment]
Loading maps and other features uses tcp directly. Could that be the reason?
Things only work when we disable this setting 👇

![Screenshot_20210116-201612_AdGuard.jpg](https://user-images.githubusercontent.com/67317350/104821389-c49efa80-583b-11eb-9719-976a96d94226.jpg)

**Comment by ameshkov** [comment]
> Loading maps and other features uses tcp directly. Could that be the reason?
> Things only work when we disable this setting 👇

Uh, this may mean that there's actually a bug in AdGuard that messes with the TCP connection.

We're planning to publish a minor update of AdGuard soon, and we could disable filtering for AmiGO there - as a temporary solution. Meanwhile, we'll try to figure out the real cause and properly fix it later.
