### ISSUE TITLE
Svyaznoy.ru, cdek.ru и tochka.com

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/HttpsExclusions#376]
Привет,

не работают сайты, пока не добавишь их в исключения https-фильтрации:
https://www.svyaznoy.ru/
https://www.cdek.ru/ru/
https://tochka.com/

Мне казалось, что эти домены уже были в исключениях HTTPS:
https://forum.adguard.com/index.php?threads/ohio8-checks-me.31348/#post-179277
https://github.com/AdguardTeam/CoreLibs/issues/674

Но сейчас их нет. Прошу рассмотреть необходимость их добавления. 

Спасибо.

**Comment by Chinaski1** [comment]
Добрый день, svyaznoy.ru действительно находится в исключениях  HTTPS фильтрации по умолчанию.
Остальные два по умолчанию фильтруются, но я не встретил проблем при их использовании.
Вы не могли бы, пожалуйста, указать версию AdGuard, версию браузера и ОС, на которой воспроизводится указанная проблема?

**Comment by ammnt** [comment]
@Chinaski1, в обоих конфигурациях без добавления в исключения либо белый экран, либо бесконечная загрузка (редиректы):
1. macOS 11.1 Big Sur, Safari 14.0.2, AdGuard для Mac 2.5.1
2. Windows 10 Home 20H2, Google Chrome 88, AdGuard для Windows 7.5.3

На Windows приложение стоит с 20 июня, но корневого домена svyaznoy.ru, например, там не было - я его сегодня добавил вручную. Только после этого заработало.

**Comment by Chinaski1** [comment]
Добавили указанные сайты в HTTPS исключения.
Спасибо за предоставленную информацию :)

**Comment by ammnt** [comment]
@Chinaski1, спасибо вам! my.tochka.com и z.tochka.com наверно тоже можно удалить, раз корневой tochka.com теперь в исключениях. А svyaznoy.ru я так и не нашел в списках - только с www. FYI.
