### ISSUE TITLE
https://ihelper.mts.by/selfcare/ 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/HttpsExclusions#39]
It won't open until added to the HTTPS exceptions list.

### Before
![image](https://user-images.githubusercontent.com/15856304/32858569-9d3c622a-ca54-11e7-8526-7dd80eecedd6.png)

### After
![image](https://user-images.githubusercontent.com/15856304/32858539-81a559b8-ca54-11e7-9985-ed1615c13bd4.png)

**Comment by vozersky** [comment]
added https://github.com/AdguardTeam/HttpsExclusions/commit/014d34686f620fc3331edb57ed477edba21859d8

**Comment by zubrRB** [comment]
Они баннерную рекламу размещают, которая блокируется вашими правилами в фильтрах. Но так как в исключениях...

<details><summary>Screenshot:</summary>

![mts](https://user-images.githubusercontent.com/50718960/144449472-d815602d-6b1c-4a42-ae32-432077ca8ce3.png)
</details><br/>
