### ISSUE TITLE
express-credit.in.ua - add to the HTTPS exceptions

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/HttpsExclusions#40]
Возникает ошибка с сайтом https://express-credit.in.ua/

После перезагрузки компьютера - сайт не работает, браузеры IE, Edge пишут что ошибка шифрования TLS.

Если в Adguard убрать галочку "Фильтровать HTTPS протокол", то сайт начинает работать (если вернуть её обратно - тоже работает). Но каждый раз после перезагрузки это делать не самое удобное решение.

**Comment by vozersky** [comment]
добавлено https://github.com/AdguardTeam/HttpsExclusions/commit/ae00617df2863a0b21dfc2dca89222ff1738a973
