### ISSUE TITLE
Add hpcloud.hp.com and hpcloud.hp.net to the HTTPS exclusions list

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/HttpsExclusions#405]
@planet0 commented on [Fri May 07 2021](https://github.com/AdguardTeam/AdguardForWindows/issues/3780)

HP Support Assistant is not able to function with an account when AdGuard is installed due to HTTPS filtering.

https://www8.hp.com/us/en/campaigns/hpsupportassistant/pc-diags.html
https://www.microsoft.com/en-us/p/hp-support-assistant/9wzdncrdrbfb?activetab=pivot%3Aoverviewtab

Originally posted in https://github.com/AdguardTeam/AdguardFilters/issues/81623.

Could we add `hpcloud.hp.com` and `hpcloud.hp.net` to the default HTTPS exclusions list?
I feel as though this would be beneficial for all HP computer users to avoid this issue occurring with AdGuard.

+

https://github.com/AdguardTeam/AdguardFilters/issues/81623#issuecomment-841654317

**Comment by ameshkov** [comment]
@Alex-302 sure, add it to the `issues.txt`

**Comment by Chinaski1** [comment]
Added to the exclusions list.

**Comment by planet0** [comment]
The exclusions have worked and allows HP Support Assistant to function properly, thank you!
