### ISSUE TITLE
Some Bank Websites Should Be Excluded

### ISSUE THREAD

**Issue by bkrcrc** [AdguardTeam/HttpsExclusions#41]
1 - https://www.qnbfinansbank.com/
1.1 - https://internetsubesi.qnbfinansbank.com/Login/LoginPage.aspx
2 - https://www.abank.com.tr/
2.1 - https://online.abank.com.tr/Login/FirstLevel
3 - https://www.atbank.com.tr/
3.1 - https://internetsubesi.atbank.com.tr/WebApplication.UI/default.aspx

Please check the bank website above. These are Turkish bank websites and "AdGuard Personal CA" is filterin 'em.
Thanks

**Comment by vozersky** [comment]
Thanks! Added https://github.com/AdguardTeam/HttpsExclusions/commit/3afcf8c01c613ebe996fe4e5b583f84184ad6568
