### ISSUE TITLE
Some other banks should be excluded

### ISSUE THREAD

**Issue by jiripolacek** [AdguardTeam/HttpsExclusions#42]
Moneta
domain: internetbanka.cz
https://ibs.internetbanka.cz/

Česká spořitelna (new online banking)
domain: csas.cz
https://bezpecnost.csas.cz/
https://george.csas.cz/

Sberbank
domain: sberbankcz.cz
https://ob.sberbankcz.cz/

**Comment by vozersky** [comment]
thanks! added https://github.com/AdguardTeam/HttpsExclusions/commit/3afcf8c01c613ebe996fe4e5b583f84184ad6568
