### ISSUE TITLE
web.postman.co

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/HttpsExclusions#421]
Hello,

please, add domain of Postman GUI web version to the HTTPS exclusions list because AdGuard intervening in some responses. For example:

![image](https://user-images.githubusercontent.com/45385632/133151028-47aaece3-be01-44f9-99e5-482576962a9a.png)

Thank you.
Cheers! 😙

**Comment by ameshkov** [comment]
CC @Alex-302, может лучше в фильтрах это решить и не влезать

**Comment by Alex-302** [comment]
@ammnt Please test:
`@@||orion-http.gw.postman.co/v*/request$document`

**Comment by ammnt** [comment]
> @ammnt Please test:
> `@@||orion-http.gw.postman.co/v*/request$jsinject,elemhide,extension`

Works perfect! Thank you!
