### ISSUE TITLE
Add Brazilian payment wallets 

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/HttpsExclusions#423]
Add Brazilian payment wallets  (similar to PayPal)

- PagSeguro  (https://pagseguro.uol.com.br, https://acesso.pagseguro.uol.com.br)
- Mercado Pago (https://www.mercadopago.com.br)
- Ame (https://www.amedigital.com/)
- PicPay (https://www.picpay.com)
- PagBrasil (https://www.pagbrasil.com)
- Tom (https://www.ton.com.br)
- Stone (https://www.stone.com.br, https://conta.stone.com.br)
- PagBrasil (https://www.pagbrasil.com)

**Comment by Chinaski1** [comment]
Done
