### ISSUE TITLE
Add  Brazilian banks

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/HttpsExclusions#424]
Add  Brazilian banks

- Unicred (www.unicred.com.br, https://novounicredinternet.e-unicred.com.br)
- Sicredi (https://www.sicredi.com.br)
- Banco do Nordeste (https://www.bnb.gov.br, https://nel.bnb.gov.br/)
- Banco da Amazônia (https://www.bancoamazonia.com.br, https://www2s.bancoamazonia.com.br/netbanking)
- Banco BV (https://www.bv.com.br, https://www4.bancobv.com.br)
- Banco BMG (https://www.bancobmg.com.br)
- C6 Bank (https://www.c6bank.com.br)
- Next (https://next.me)
- Banco Original (https://www.original.com.br, https://meu.original.com.br/Original-InternetBanking-Webapp)
- Banco Mercantil do Brasil (https://mercantildobrasil.com.br)
- Banco PAN (https://www.bancopan.com.br, https://webbanking.bancopan.com.br/login)
- Paraná Banco (https://www.paranabanco.com.br, https://www.netbankparana.b.br)
- BTG Pactual (https://www.btgpactual.com)
- Rico (https://www.rico.com.vc)
- Clear (https://corretora.clear.com.br, https://login.clear.com.br/pit/login, https://pro.clear.com.br)
- Banco Safra (https://www.safra.com.br, https://www.ib.safra.com.br)

**Comment by Chinaski1** [comment]
Done
