### ISSUE TITLE
Add payment wallets

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/HttpsExclusions#425]
Add payment wallets

- Revolut (https://www.revolut.com, https://app.revolut.com/start)
- Rede (https://www.userede.com.br, https://meu.userede.com.br/login)
- Cielo (https://www.cielo.com.br, https://minhaconta2.cielo.com.br/login)
- RecargaPay (https://recargapay.com.br)
- Adyen (https://www.adyen.com)

**Comment by Chinaski1** [comment]
Done
