### ISSUE TITLE
Add one more URL of the Receita Federal do Brasil as sensitive

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/HttpsExclusions#426]
- https://receita.fazenda.gov.br (https://cav.receita.fazenda.gov.br/autenticacao/login , https://coletorcafir.receita.fazenda.gov.br/coletor/index.jsf)

https://github.com/AdguardTeam/HttpsExclusions/issues/169

**Comment by Chinaski1** [comment]
cav.receita.fazenda.gov.br - domain is already added to the exclusions (Banks.txt)
