### ISSUE TITLE
fiz.tavrich.ru

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/HttpsExclusions#436]
@adguard-bot commented on [Fri Oct 01 2021](https://github.com/AdguardTeam/AdguardFilters/issues/96192)

### Issue URL (Incorrect Blocking)
 [https://fiz.tavrich.ru/elf/app/main?wicket-crypt=bXG6vJk_coM&main=priv&replace=main&context=0](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Ffiz.tavrich.ru%2Felf%2Fapp%2Fmain%3Fwicket-crypt%3DbXG6vJk_coM%26main%3Dpriv%26replace%3Dmain%26context%3D0)
### Comment
Username: @rakleed
> Сайт постоянно перезагружается с включённым AdGuard

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/rldnP13.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/1wkRJPM.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.6.1
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Hide your Referrer from third-parties (fiz.tavrich.ru), <br>Hide your User-Agent ()
DNS filtering: | server: `https://dns.cloudflare.com/dns-query`<br>
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
Referrer: | [https://fiz.tavrich.ru/elf/app/main?wicket-crypt=bXG6vJk_coM&main=priv&replace=main&context=0](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Ffiz.tavrich.ru%2Felf%2Fapp%2Fmain%3Fwicket-crypt%3DbXG6vJk_coM%26main%3Dpriv%26replace%3Dmain%26context%3D0)

---

@Alex-302 commented on [Mon Oct 18 2021](https://github.com/AdguardTeam/AdguardFilters/issues/96192#issuecomment-945844982)

@rakleed Чем ломается? Без аккаунта я не проверю.

---

@rakleed commented on [Mon Oct 18 2021](https://github.com/AdguardTeam/AdguardFilters/issues/96192#issuecomment-945961947)

@Alex-302 вообще это сайт банка. Может просто добавите его в исключения как другие банковские сайты?

**Comment by zubrRB** [comment]
@rakleed при необходимости самому можно добавлять домены в список HTTPS-исключений.
