### ISSUE TITLE
edge-mqtt.facebook.com (Messenger for Desktop)

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/HttpsExclusions#448]
AdGuard cannot filter [Messenger for Desktop](http://messenger.com/desktop) unless `edge-mqtt.facebook.com` is added into HTTPS exclusions.

<img width="641" alt="Screen Shot 2021-12-22 at 8 00 17 pm" src="https://user-images.githubusercontent.com/65204836/147071055-d3a81b10-be8c-4ee7-bf09-55d5990e663e.png">

> @planet0 commented on [Wed Dec 22 2021](https://github.com/AdguardTeam/AdguardFilters/issues/104095#issuecomment-999416489)
> 
> In Console logs, I see for AdGuard:
> 
> `Can't find log object in the pool of an active log objects:[info="tls://edge-mqtt.facebook.com:443", rule="" appName="Messenger"]`
> 
> @planet0 commented on [Wed Dec 22 2021](https://github.com/AdguardTeam/AdguardFilters/issues/104095#issuecomment-999419736)
> 
> Adding `edge-mqtt.facebook.com` to the HTTPS exclusions fixed it. Is this something we could add by default to the list, or is the domain a privacy/tracking related one?
> 
> <img alt="image" width="812" src="https://user-images.githubusercontent.com/65204836/147069079-1367476f-0e18-4778-84e6-2aff01df1139.png">

https://github.com/AdguardTeam/AdguardForMac/issues/1020
https://github.com/AdguardTeam/AdguardFilters/issues/104095

**Comment by planet0** [comment]
Never mind, the app uses TLS to bypass filtering and so it also wants more domains to be excluded from AdGuard HTTPS filtering... I'll just remove Messenger from AdGuard filtering altogether.

`Can't find log object in the pool of an active log objects:[info="tls://graph.facebook.com:443", rule="" appName="Messenger"]`

`Can't find log object in the pool of an active log objects:[info="tls://web.facebook.com:443", rule="" appName="Messenger"]`

**Comment by sfionov** [comment]
Messenger app doesn't trust custom CAs. While it is sending "unknown ca" alerts for most domains, it doesn't do it for this domain, so this domain remains broken. It is not recommended to turn on HTTPS filtering for this app.
