### ISSUE TITLE
More banking apps: QNB Finansbank and Garanti Cep

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/HttpsExclusions#45]
https://play.google.com/store/apps/details?id=com.finansbank.mobile.cepsube
https://play.google.com/store/apps/details?id=com.garanti.cepsubesi&hl
https://play.google.com/store/apps/details?id=com.freecharge.android - wallet

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #1638](https://github.com/AdguardTeam/AdguardForAndroid/issues/1638) via [**ZenHub**](https://www.zenhub.com/)
