### ISSUE TITLE
add https filtering exclusions

### ISSUE THREAD

**Issue by chefB90** [AdguardTeam/HttpsExclusions#452]
mijn.belastingdienst.nl
myaccount.google.com
trader.degiro.nl
mijn.overheid.nl
deribit.com
solium.com
digid.nl
geldvoorelkaar.nl
login.live.com
account.live.com

protonmail.com
outlook.live.com
mail.google.com

**Comment by ameshkov** [comment]
At least half of them are full of trackers and ads and aren't eligible to be added to the default list.

Please open a new issue and filter those out. Also, please supply the description for the domains, what exactly they are for.
