### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by nualal** [AdguardTeam/HttpsExclusions#46]
Every time I try to login to some app or website I have paid for, no matter what browser I use, I keep getting redirected about 4 times per app and can not get anywhere?? Any ideas??

**Comment by vozersky** [comment]
Hi! Sorry, but this is a wrong repo for this type of questions, could be a filtering problem, but it's better to create issue [here](https://github.com/AdguardTeam/AdguardFilters/issues) and provide more details so we can find the origin of the issue.
