### ISSUE TITLE
Australia - Bank and Sensitive Exclusions

### ISSUE THREAD

**Issue by TheMousyIntrovert** [AdguardTeam/HttpsExclusions#461]
Hi,

I'd appreciate it if some sites could be included in your exclusion lists.

**Banking, Payments, and Credit Info**
- suncorp.com.au (bank)
- internetbanking.suncorpbank.com.au (online banking)
- ebay.com.au
- amazon.com.au
- gumtree.com.au (market trading)
- aldimobile.com.au (mobile recharging)
- hbf.com.au (health insurance)
- steampowered.com (not sure, but payment information goes through Steam, or more specifically store.steampowered.com)

**Sensitive**
- my.gov.au (government services: Medicare, Centrelink, ATO, etc)
- ato.gov.au (tax)
- medicareaustralia.gov.au (government health)
- jobsearch.gov.au (government job search)
- centrelink.gov.au (government payments)
- mygovid.gov.au (identity verification: passport, license, birth certificate, etc)
- passwords.google.com (password manager)

Thank you for your help! 😄

Kind regards,
Bree

**Comment by Chinaski1** [comment]
Excluded banking sites from HTTPS filtering.
`gov.au` domains are already excluded.
Regarding other domains, I don't think there is a need to exclude these services:

```ebay.com.au
amazon.com.au
gumtree.com.au (market trading)
aldimobile.com.au (mobile recharging)
hbf.com.au (health insurance)
steampowered.com (not sure, but payment information goes through Steam, or more specifically store.steampowered.com)```
