### ISSUE TITLE
More AUS adguard https exclusions

### ISSUE THREAD

**Issue by aussiefella74** [AdguardTeam/HttpsExclusions#464]
Hi, could you please add the following addresses to your https exclusion list?

https://wise.com/login
https://wise.com/au
https://www.paypal.com/signin
https://secure.selfwealth.com.au
https://portfolio.sharesight.com
https://login-au.computershare.com
https://ibank.bankfirst.com.au/desktop/signon/login.aspx

Thanks so much. Aussie.

**Comment by Chinaski1** [comment]
`Wise.com` was added to the exclusions list.

Other domains are already there.
