### ISSUE TITLE
Add Metro Bank to exclusions

### ISSUE THREAD

**Issue by m00t316** [AdguardTeam/HttpsExclusions#468]
The URL is: https://www.metrobankonline.co.uk

**Comment by m00t316** [comment]
I forgot to include https://personal.metrobankonline.co.uk/login/ to exclusions. Can this URL be added too?

**Comment by zloyden** [comment]
As far as I know, it's not needed due to [exclusion](https://github.com/AdguardTeam/HttpsExclusions/pull/470/files#diff-c4f3d28afb4bb58078b835f1b0a077bfdbcba307e6a2947ff6a24208466df322R1540).

**Comment by bkrucarci** [comment]
Thanks @zloyden ! this part of AdGuard's github seemed a bit unattended

**Comment by zloyden** [comment]
You are welcome. If you face the problem in this repo, feel free to mention `@Aydinv13 @Chinaski1 @zzebrum`.
