### ISSUE TITLE
Remove `eff.org` from Firefox exclusions

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/HttpsExclusions#471]
Could you please remove the domain `eff.org` from Firefox exclusions? Since the site has some elements which should be blocked. For example, https://github.com/AdguardTeam/AdguardFilters/issues/117026

**Comment by rakleed** [comment]
@Aydinv13 @Chinaski1

**Comment by zzebrum** [comment]
@rakleed there is a problem with HTTPS Everywhere browser extension for firefox being hosted on the `eff.org` website - it can't be updated. That's why the app ended up the exclusions on our side.

**Comment by rakleed** [comment]
@zzebrum and there is no option to add a more specific subdomain?

**Comment by Alex-302** [comment]
Just remove exclusion in your app.

**Comment by rakleed** [comment]
@Alex-302 I know about it, but doing it on each device isn't convenient. So @zzebrum, could you add a more specific subdomain?

**Comment by Alex-302** [comment]
Impossible

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/172133645-fffc3b8e-c54b-4400-9eb7-54a917e042a7.png)


</details>
