### ISSUE TITLE
Remove `www` prefix from domains in HttpsExclusions

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/HttpsExclusions#473]
После исправления https://github.com/AdguardTeam/AdguardForWindows/issues/4240 для отображения в браузерном помощнике (и фильтрации) не имеет значения указание префикса `www` у прописанных по умолчанию доменов в разделе HTTPS-исключений.  
Всего там прописано 14 доменов с префиксом. Может унифицировать их с остальными и удалить префикс `www`?

<details><summary>Screenshot:</summary>

![HTTPS](https://user-images.githubusercontent.com/50718960/168327531-97b13f12-f6e7-4b92-88c1-e7535b54c983.png)
</details><br/>

**Comment by zzebrum** [comment]
эта задача еще не доехала до релиза AdGuard для windows

**Comment by zubrRB** [comment]
Пока в пятой найтли.

**Comment by zubrRB** [comment]
Вчера доехала...

**Comment by sfionov** [comment]
@zubrRB Та задача была про неверное отображение. Замена доменов на аналогичные без www же это изменение поведения, т.к. запись с www не включает сабдомены, а без www - включает.

Если есть какие-то примеры, что на сабдоменах каких-то из этих доменов тоже не нужна фильтрация, то их, конечно, нужно добавить. 

Но в целом это совсем не про тот фикс.

**Comment by zubrRB** [comment]
ЯсноПонятно!
