### ISSUE TITLE
New ProtonMail domain

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/HttpsExclusions#475]
### Summary
Proton AG designed their website from https://protonmail.com/ to https://proton.me/.

### References
https://github.com/AdguardTeam/HttpsExclusions/blob/432c9185ffa32bb62bfe3730826c96d0314d5112/exclusions/sensitive.txt#L5

 - https://proton.me/news/new-visual-universe
- https://github.com/AdguardTeam/HttpsExclusions/issues/469

**Comment by dexteragc** [comment]
@piquark6046 This was Fixed in 346cb7191f327e5dfdc0137e4ca9db15f1328ecb
