### ISSUE TITLE
https://online.cosmosbank.in/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/HttpsExclusions#50]
https://online.cosmosbank.in/

![image](https://user-images.githubusercontent.com/15856304/34248777-ec8c1f44-e63f-11e7-86e9-ff7de6227c7d.png)

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/HttpsExclusions/commit/ef99e6cc206dd51f45f6fb8f223a0484bc3088d7
