### ISSUE TITLE
Any way to add exclusions yourself in the Adguard Home product?

### ISSUE THREAD

**Issue by Landorin-GH** [AdguardTeam/HttpsExclusions#509]
Hi,

does the current Adguard home allow to add exclusions yourself either via GUI or by editing a file or something? If not, could this be considered to add as custom option?

I face the situation that I would like to exclude all my internal company's websites. Yet since some of them are also available externally to customers as well as for business and personal reasons I do not want to disclose this data here I was wondering if I can add these exclusions just for myself? I currently run Adguard Home on Docker.

If I knew which files to edit I would gladly do it myself but the files in this repo do not seem to reflect the files of the local installation 1:1 .

**Comment by ameshkov** [comment]
I am not sure if this question is relevant to this repo, AGH does not do HTTPS filtering.

Generally, in AdGuard Home you can add custom filtering rules and exclude any domains there.
