### ISSUE TITLE
"enpara.com" and its applications Should Be Excluded

### ISSUE THREAD

**Issue by bkrucarci** [AdguardTeam/HttpsExclusions#51]
1 - https://www.qnbfinansbank.enpara.com/
2 - https://internetsubesi.qnbfinansbank.enpara.com/Login/LoginPage.aspx (individual)
3 - https://sirketiminternetsubesi.qnbfinansbank.enpara.com/Login/LoginPage.aspx (Business)

![enpara](https://user-images.githubusercontent.com/15933805/34338818-6511c370-e97d-11e7-9d62-bc4eaf43db28.png)

and they have applications on Google Play, I am not using them but AdGuard for Android may filter 'em. Please exclude these applications for AdGuard for Android as well.

https://play.google.com/store/apps/details?id=finansbank.enpara
https://play.google.com/store/apps/details?id=finansbank.enpara.sirketim

Thanks,
Bekir

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/HttpsExclusions/commit/978ff8bf03cf83129c85f35afb7cf45a0bfbb6d1 added, thanks

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/1710
