### ISSUE TITLE
Add new `id.yandex.*` domains

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/HttpsExclusions#513]
`passport.yandex.*` now redirect to `id.yandex.*`.
https://github.com/AdguardTeam/HttpsExclusions/blob/b89c0fbb122b38dad38ec8962d42d06252f169d4/exclusions/sensitive.txt#L35-L40

**Comment by krystian3w** [comment]
I see still works `yandex.pl` with `passport.yandex.pl`.
