### ISSUE TITLE
...

### ISSUE THREAD

**Issue by Bazixv13** [AdguardTeam/HttpsExclusions#518]
banking websites:
https://ing.pl
https://login.ingbank.pl/

**Comment by krystian3w** [comment]
First may don't need protection, but second exist on list:

https://github.com/AdguardTeam/HttpsExclusions/blob/c312c6a1937a87a1b4c9e1a65482ea14f5bb63df/exclusions/banks.txt#L1306
https://github.com/AdguardTeam/HttpsExclusions/blob/c312c6a1937a87a1b4c9e1a65482ea14f5bb63df/exclusions/banks.txt#L1542

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/HttpsExclusions/issues/52
