### ISSUE TITLE
Add polish bank domains 

### ISSUE THREAD

**Issue by upr-kmd** [AdguardTeam/HttpsExclusions#522]
Please add the following Polish bank domains to the exclusions in HTTPS filter:
ipko.pl
pkobp.pl
inteligo.pl
mbank.pl
citibank.pl
citibankonline.pl
bnpparibas.pl
bosbank.pl
pocztowy.pl
bankbps.pl
credit-agricole.pl
dnb.pl
ing.pl
nestbank.pl
plusbank.pl
sgb.pl
santander.pl

**Comment by krystian3w** [comment]
#518 - why `ing.pl` need protection?
