### ISSUE TITLE
bank app to add

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/HttpsExclusions#54]
please add this app to the exception list 
https://play.google.com/store/apps/details?id=com.otsar.nativeapp

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #1699](https://github.com/AdguardTeam/AdguardForAndroid/issues/1699) via [**ZenHub**](https://www.zenhub.com/)

**Comment by vozersky** [comment]
@dzamyshlyayeva apps go to the prod rep
