### ISSUE TITLE
Add Plusnet to exclusion list

### ISSUE THREAD

**Issue by ddrury** [AdguardTeam/HttpsExclusions#544]
Please add English ISP [plus.net](https://www.plus.net)

**Comment by ddrury** [comment]
Without the exclusion, Firefox won't connect

**Comment by Alex-302** [comment]
@zzebrum 

@ddrury 

I can't reproduce

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/HttpsExclusions/assets/8361299/c028ef76-ae72-42da-8579-fba2406058ea)


</details>

**Comment by zloyden** [comment]
Also can't reproduce on my end.
