### ISSUE TITLE
Protonmail

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/HttpsExclusions#55]
As reported by one of our users:

"Hi, ProtonMail (mail.protonmail.com and beta.protonmail.com) should be
added to the list of HTTPS filtering exceptions as it contains
sensitives informations (access to encrypted email account) and should
therefore not be filtered. Also, filtering seems to create loading
problem (that’s the reason I initially excluded ProtonMail) : I was
unable to login and may requests failed recently (after I started to
use AdGuard). Giving that ProtonMail is a no-ad service, I think it is
fair to add it to excluded websites and trust it."

**Comment by vozersky** [comment]
i didn't notice any loading problems so far
please provide more details to the appropriate platform repo
