### ISSUE TITLE
CrowdStrike Falcon URLs need to be whitelisted from ssl/tls inspection

### ISSUE THREAD

**Issue by syndicate0017** [AdguardTeam/HttpsExclusions#553]
ts01-b.cloudsink.net, lfodown01-b.cloudsink.net, ts01-laggar-gcw.cloudsink.net, lfodown01-laggar-gcw.cloudsink.net, ts01-lanner-lion.cloudsink.net, lfodown01-lanner-lion.cloudsink.net, ts01-gyr-maverick.cloudsink.net, lfodown01-gyr-maverick.cloudsink.net

These URLs require direct connection as these are URLs that talk to CrowdStrike’s antivirus service which performs its own SSL/TLS inspection on traffic designated for these domains.

**Comment by Alex-302** [comment]
Please show screenshot of an error.
