### ISSUE TITLE
Specialized Electronic Payment Institutions in Taiwan

### ISSUE THREAD

**Issue by HJ-zhtw** [AdguardTeam/HttpsExclusions#558]
全盈支付金融科技股份有限公司 All Win Fintech Company Limited
`pluspay.com.tw`

全支付電子支付股份有限公司 PXPay Plus Co., Ltd.
`pxpayplus.com`

悠遊卡股份有限公司 EASYCARD CORPORATION
`easycard.com.tw`

一卡通票證股份有限公司 iPASS CORPORATION
`i-pass.com.tw`

愛金卡股份有限公司 icash Corporation
`icash.com.tw`

橘子支行動支付股份有限公司 GAMA PAY Co.,Ltd.
`gamapay.com.tw`

歐付寶電子支付股份有限公司 O’Pay Electronic Payment Co., Ltd.
`opay.tw`

簡單行動支付股份有限公司 ezPay Co., Ltd.
`ezpay.com.tw`

**Comment by Alex-302** [comment]
> pluspay.com.tw
> easycard.com.tw
> icash.com.tw
> gamapay.com.tw
> opay.tw
> ezpay.com.tw

I'm not sure we should exclude it.
