### ISSUE TITLE
Azerbaijan bank site names

### ISSUE THREAD

**Issue by adreporter01** [AdguardTeam/HttpsExclusions#57]
accessbank.az
afb.az
agbank.az
amrahbank.az
atabank.com
azerturkbank.az
ibar.az
asb.az
bankavrasiya.az
btb.az
bmibaku.az
bankofbaku.com
bankrespublika.az
cbar.az
vtb.az
expressbank.az
gunaybank.com
xalqbank.az
kapitalbank.az
muganbank.az
naxcivanbank.az
nbcbank.az
nikoil.az
nbp.az
pashabank.az
rabitabank.com
banksilkway.az
turanbank.az
unibank.az
yapikredi.com.az
ziraatbank.az

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/HttpsExclusions/commit/13390d4f7b4e903dd5c7906d688a463b67616a67  added almost all of them

####
http://eng.bmibaku.az/ - Do not trust.
https://www.expressbank.az/ - Do not trust. (Tried to follow the link.- http://app4555.funnyhost-interesting92.loan/?utm_medium=NQ3aDvyuBCtafRQJPeFC66tm%2bMNW8T%2baflxP0d0AJGo%3d&t=main4)

http://www.nbp.az/about_bank.html - Do not trust.
http://www.rabitabank.com/az/order_card - There is no HTTPS.
####
