### ISSUE TITLE
Paying systems

### ISSUE THREAD

**Issue by adreporter01** [AdguardTeam/HttpsExclusions#58]
https://www.million.az/
https://www.hesab.az/
https://portmanat.az/
http://goldenpay.az/

**Comment by Revertron** [comment]
Spam :)

**Comment by TheHasagi** [comment]
Simple pay-online systems, nothing unusual.

**Comment by vozersky** [comment]
added three of them https://github.com/AdguardTeam/HttpsExclusions/commit/93289cde3277ccfac93d27b1071f5c1d2b0ced6c
