### ISSUE TITLE
Add Veridian & Transamerica

### ISSUE THREAD

**Issue by panzer-arc** [AdguardTeam/HttpsExclusions#583]
Please add this credit union to the allow-list:
veridiancu.org
and this investment/retirement firm:
secure2.transamerica.com
participant.transamerica.com

**Comment by Alex-302** [comment]
@panzer-arc Is transamerica.com used to work with the money directly? I can't register on this site and I don't know what functionality is available in the account.

**Comment by panzer-arc** [comment]
It is used to manage retirement accounts, such as a 401(k). They are like a brokerage in that sense.

**Comment by Alex-302** [comment]
Ok then.
