### ISSUE TITLE
GOG launcher https exclusions

### ISSUE THREAD

**Issue by MatthiasDillen** [AdguardTeam/HttpsExclusions#586]
I have Adguard Home running on Raspberry Pi, but GOG seems to have troubles (with Heroic games launcher on Linux), I noticed there is a similar issue #456 about it but for the Windows client. According to that issue these should be added to the https exclusions. Is it possible to add them myself in a custom list somewhere? I cant find any info/config about it. Or is it only possible via this repo?

content-system.gog.com
gamesdb.gog.com
notifications.gog.com
marketing-sections.gog.com
api.gogalaxy.com
auth.gog.com
users.gog.com
cdn-akamai-ec.gog-services.com
cdn.gog.com
presence.gog.com
gameplay.gog.com
insights-collector.gog.com
external-accounts.gog.com

**Comment by piquark6046** [comment]
As far as I know, AdGuard Home cannot decrypt a client's traffic encrypted by TLS.

**Comment by MatthiasDillen** [comment]
I fixed it with dnsmasq:
server=/gog.com/1.1.1.1
