### ISSUE TITLE
Bank website

### ISSUE THREAD

**Issue by cemasri** [AdguardTeam/HttpsExclusions#61]
The addresses of `finansbank.com.tr` and `internetsubesi.finansbank.enpara.com `sites changed (moved to qnb domain). 

New addresses:
`qnbfinansbank.com`
`qnbfinansbank.enpara.com`

Also this address must on the https list. Identity information etc. wants.
`https://basvuru.seninbankan.com.tr/YourBank`

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/HttpsExclusions/commit/e242f3b4576311103467c153b02ee9415b2b1e7d
