### ISSUE TITLE
Banking website exclusion

### ISSUE THREAD

**Issue by maspiter** [AdguardTeam/HttpsExclusions#620]
Please add fintro.be to the banking websites exclusions list for HTTPS DPI.

**Comment by dgita24** [comment]
I don't see Bank Of Ireland in the bank exclusion list. Possible I missed it but I've searched several different key words. Could it be added please. 

https://personalbanking.bankofireland.com/bank/sepa/365-online/

**Comment by dgita24** [comment]
Thank you
