### ISSUE TITLE
tdameritrade.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/HttpsExclusions#63]
> My TD Ameritrade account will not function with Adguard Ad Blocker enabled even when the filters are applied allowing access to TD Ameratrade. The technicians at TDA all concur it is something Adguad must fix. I cannot have the ad blocked disabled but I must have access to my trading account. Can you fix this issue?

https://www.tdameritrade.com/home.page

Our customers can't log in to their Ameritrade accounts, adding the website to the HTTPS exclusions helps.

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/HttpsExclusions/commit/e242f3b4576311103467c153b02ee9415b2b1e7d

**Comment by dimasmoosa** [comment]
The home page works but searching a stock or going to other links still freezes the web page.

**Comment by vozersky** [comment]
@dimasmoosa have you added the exclusion in your app? it will not be automatically updated until the new version is out

**Comment by dimasmoosa** [comment]
Yes. 
![adguard td ameritrade exclusion](https://user-images.githubusercontent.com/16375574/40797009-cc743de0-64d4-11e8-91c6-b1862fb5a0c3.PNG)

To reproduce the issue:
1) Go to https://www.tdameritrade.com/home.page
2) Log in
3) Click on anything (I went to search bar and searched 'AAPL' ticker symbol)
4) Web page becomes unresponsive

If Adguard is disabled, this issue doesn't occur.

**Comment by ameshkov** [comment]
You need to add the domain only: `tdameritrade.com`

**Comment by rnapier** [comment]
@ameshkov I also need to add `ameritrade.com`, not just `tdameritrade.com`.
