### ISSUE TITLE
Add banking site to exclusion

### ISSUE THREAD

**Issue by rockstarrocks** [AdguardTeam/HttpsExclusions#69]
Please add https://www.bobibanking.com/ to the exclusions for https scanning. It's for site of Indian bank named "Bank Of Baroda", a major portion of which is owned by Indian Govt.

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/HttpsExclusions/commit/6a986e68e9c4c0cfe38560661830c3dd9c06a466
