### ISSUE TITLE
Add some MY banking websites to the exclusion list.

### ISSUE THREAD

**Issue by ufufufu** [AdguardTeam/HttpsExclusions#73]
Hello, I request that some Malaysia's online bank list to be included in the list:-

https://www.allianceonline.com.my/
https://www.cimbclicks.com.my/
https://www.maybank2u.com.my/
https://www.mybsn.com.my/
https://www.pbebank.com/

Thanks.

**Comment by vozersky** [comment]
Hi! Added, thanks!
https://github.com/AdguardTeam/HttpsExclusions/commit/fe5b23600b62726834a37b9c71dd114badf3db70
