### ISSUE TITLE
TunnelBear filtering bug

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/HttpsExclusions#8]
Using TunnelBear browser extension disrupts filtering, possibly due to TunnelBear domain being in HTTPS exclusions list. 

More details here:
https://forum.adguard.com/index.php?threads/21120/#post-135396

**Comment by vbagirov** [comment]
@vozersky could you please test it? Doesn't look like removing only tunnelbear.com from the exclusions does the trick.

**Comment by vozersky** [comment]
can't reproduce
