### ISSUE TITLE
Bank list: BBVA, Caixa Enginyers, ING and Triodos

### ISSUE THREAD

**Issue by redpay** [AdguardTeam/HttpsExclusions#81]
I would like to requests the following Banks are added to the banking exclusion list:

Caixa Enginyers: https://www.caixa-enginyers.com/

BBVA: https://www.bbva.es

Triodos: https://www.triodos.es/

ING: https://www.ing.es

**Comment by vozersky** [comment]
@redpay  added, thanks!

https://github.com/AdguardTeam/HttpsExclusions/commit/c23223bed02da2b840f56ce2cd897435f40115c1
