### ISSUE TITLE
Additional banks to add

### ISSUE THREAD

**Issue by gregforcey** [AdguardTeam/HttpsExclusions#82]
Please add the following financial institutions to the list:
```
vystarcu.org
penfed.org
navyfederal.org
discover.com
cnb.com
tiaa.org
ml.com
vanguard.com
schwab.com
```

**Comment by vozersky** [comment]
Hi.
Thank you!
Added all of them plus mymerrill.com
The exclusions list will be updated in the next release.
https://github.com/AdguardTeam/HttpsExclusions/commit/748fe610606d5c79d025c97238089f23bdc48205
