### ISSUE TITLE
Request additional https Exclusions

### ISSUE THREAD

**Issue by GyN4Dzim** [AdguardTeam/HttpsExclusions#98]
Dear AdGuard Team:

I would greatly appreciate your adding the following banking domains to the https Exclusions list:

docfcu.org
campuscu.com
tsp.gov

Please advise by return message to skimofenix@minoplis.com if you can do this, and if you have done this.

Thank you for your assistance,
Skimofenix

**Comment by vozersky** [comment]
@GyN4Dzim 

Hello! Thanks for reporting it to us. Added https://github.com/AdguardTeam/HttpsExclusions/commit/b7264b4077d00936580608625585cc62bd68e57e
HttpsExclusions list is going to be updated in the next app build.
